---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
data:
  config.json: |
    {
      "port": 3001,
      "endpoint": {
        "address": "https://echo-server.nsxbg.cna-demo.ga",
        "type": "web",
        "versions": ["blue", "green"]
      },
      "probe": {
        "interval": 10
      },
      "sample": {
        "interval": 1000,
        "max": 600
      },
      "graph": {
        "colors": ["blue", "green"]
      }

    }

